### ISSUE TITLE
Generate contributor list based on specified SHA or date

### ISSUE THREAD

**Issue by ThomasBurleson** [mgechev/github-contributors-list#1]
Currently the list generated is the complete list of contributors sorted by `#` of contributions (highest first).

```
githubcontrib --repo material --user angular 
\ --showlogin true --cols 7 --strategy table --format md 
\ --filter gitter-badger,bitdeli-chef | pbcopy
```

A great feature would allow a SHA to be specified that would filter only contributors SINCE (on and after the date) that SHA was created. The API would be simply `--since <SHA>`

**Comment by ThomasBurleson** [comment]
An additional feature would allow sorting based on Github Name or lastname: 

*  `--sort github_name`
*  `--sort lastname`

**Comment by mgechev** [comment]
I added an option to include custom sorting algorithms and sort by field with the built-in algorithms.

Need to research the github API a bit further in order to see how long it is going to take to implement the filter before SHA.

**Comment by mgechev** [comment]
The [latest features](https://github.com/mgechev/github-contributors-list/commit/e319fb1a133f39a13f03d729fb36a6d00bd08ef4) you introduced close this issue.
