### ISSUE TITLE
Thank you for this script!

### ISSUE THREAD

**Issue by dherault** [mgechev/github-contributors-list#16]
Just wanted to say thank you 😄 

https://github.com/dherault/serverless-offline#contributors

**Comment by dherault** [comment]
Oh btw it would be cooler to do `npx your-package-name --owner foo --repo bar > contributors.md`. Plus you could see the number of downloads on NPM!

**Comment by dherault** [comment]
Also the default `--sortOrder` should be `desc` so top top contributors would be first.

**Comment by mgechev** [comment]
Thanks for the kind words!

I'm using this bash function:

```bash
function ghcontrib() {
   repo=$(basename $(pwd))
   githubcontrib --owner mgechev --repo $repo --cols 6 --showlogin true --filter gitter-badger --sortOrder desc | pbcopy
}
```

Going to a directory and running `ghcontrib` puts everything into the clipboard.

**Comment by dherault** [comment]
`pbcopy` does not work on windows ! Maybe add a `--copyToClipboard` function and use some API to copy ?

**Comment by mgechev** [comment]
I'd prefer to keep this outside of the scope of the tool. Not sure what would be the right way to implement the `ghcontrib` function on Windows though.
