### ISSUE TITLE
Add image to README

### ISSUE THREAD

**Issue by ThomasBurleson** [mgechev/github-contributors-list#2]
I recommend that you put this image in your [GitHub-Contributors-List README](https://github.com/mgechev/github-contributors-list):

![screen shot 2016-04-06 at 1 01 34 pm](https://cloud.githubusercontent.com/assets/210413/14327430/e4bd40b0-fbf7-11e5-8429-f5de380c571b.png)

> IMO, adding nice visuals to a README always improves understanding and increases traffic/usage.

**Comment by mgechev** [comment]
Done

**Comment by ThomasBurleson** [comment]
:+1: Love it!
